name: leadrole
description: "LeadRole mobile - Your turn on camera."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.9.2


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  riverpod: ^3.0.3
  flutter_riverpod: ^3.0.3
  go_router: ^16.3.0
  http: ^1.5.0
  image_picker: ^1.2.0
  gif: ^2.3.0
  firebase_core: ^4.2.0
  cloud_firestore: ^6.0.3
  flutter_secure_storage: ^9.2.4
  dio: ^5.9.0
  video_player: ^2.10.0
  flutter_cache_manager: ^3.4.1
  shared_preferences: ^2.5.3
  equatable: ^2.0.7
  open_filex: ^4.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Thin.ttf
          weight: 100
        - asset: assets/fonts/Montserrat-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Montserrat-Light.ttf
          weight: 300
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Montserrat-Black.ttf
          weight: 900